name: 「プルリクエストコメント抽出ツール」のパッケージを作成するアクション

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Goのセットアップ
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: ビルドしてgetpr.exeを生成
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          cd getpr
          go build -o ../prtool/プルリクエストコメント抽出ツール/getpr.exe cmd/main.go
      - name: ZIPファイル作成
        run: |
          sudo apt-get install -y convmv
          cd prtool
          convmv --notest -r -f utf8 -t sjis .
          zip -r プルリクエストコメント抽出ツール.zip .

      - name: ZIPファイルのアップロード
        uses: actions/upload-artifact@v3
        with:
          name: prtool
          path: prtool
          retention-days: 1